install.packages('ISLR2')
install.packages('ROCR')
install.packages('tree')
install.packages('randomForest')
install.packages('BART')
install.packages('gbm')
install.packages('rmarkdown')
install.packages('knitr')
install.packages('caret')

#install.packages('luz')
#install.packages('torch')
#install.packages('torchdatasets')
#install.packages('torchvision')
